version: "3"

services:
  server:
    build: server
    network_mode: host
    env_file:
      - server/.env
    ports:
      - "3001:3001"
    expose:
      - 3001

  client:
    build: client
    network_mode: host
    env_file:
      - client/.env.local
    ports:
      - "3000:3000"
    expose:
      - 3000
